/* 
 * File:   main_StadiumSeating.cpp
 * Author: Elise Chue
 * Created on June 27, 2016, 12:27 PM
 * Purpose: Calculate how many tickets sold and income
 */

//System Libraries
#include <iostream>//Input/Output Stream Library
#include <iomanip> 
using namespace std;//Iostream uses the standard namespace

//User Libraries

//Global Constants

//Function Prototypes

//Execution Begins Here!
int main(int argc, char** argv) {
    //Declare variables, no doubles
    float tixA=15;//Class A ticket cost in $s
    float tixB=12;//Class B ticket cost in $s
    float tixC=9;//Class C ticket cost in $s
    int nSA,nSB,nSC;//number of seats/tickets sold for Class A-C
    //int nSB;//number of seats/tickets sold for Class B
    //int nSC;//number of seats/tickets sold for Class C
    float incA;//income generated by class A tix sold
    float incB;//income generated by class B tix sold
    float incC;//income generated by class C tix sold
    float incTTL;//Total income generated by classes A-C tix sold
    
    //Input data
    cout<<"How many tickets were sold for Class A?"<<endl;
    cin>>nSA;

    //Process data
    
    //Output data
    
    //Exit Stage Right!
    return 0;
}

